### ISSUE TITLE
sklearn.exceptions.NotFittedError: This OneHotEncoder instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

### ISSUE THREAD

**Issue by Khad515** [drginm/real-estate-tensorflow#1]
Traceback (most recent call last):
  File "C:/Tensorflow/real-estate-tensorflow-masterTest/real-estate-tensorflow-master/predict.py", line 31, in <module>
    model_inputs, _ = common_pre_post_processing.transform_inputs(values, label_encoder, onehot_encoder, x_scaler)
  File "C:\Tensorflow\real-estate-tensorflow-masterTest\real-estate-tensorflow-master\common_pre_post_processing.py", line 12, in transform_inputs
    values_df = common_categorical.encode_categorical_column(values, common.categorical_column, label_encoder, onehot_encoder)
  File "C:\Tensorflow\real-estate-tensorflow-masterTest\real-estate-tensorflow-master\common_categorical.py", line 37, in encode_categorical_column
    onehot_encoded = onehot_encoder.transform(integer_encoded)
  File "C:\Users\khadd\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\preprocessing\_encoders.py", line 726, in transform
    check_is_fitted(self, 'categories_')
  File "C:\Users\khadd\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\utils\validation.py", line 914, in check_is_fitted
    raise NotFittedError(msg % {'name': type(estimator).__name__})
sklearn.exceptions.NotFittedError: This OneHotEncoder instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

Im trying to regenarate model, but everytime get error trying to transform data.

**Comment by drginm** [comment]
Bonjour Khad515, did you try first training the model and then using the predict.py file?
